"""
api/v1/endpoints/uat.py
Local UAT report explorer endpoints.

Reads JSON artifacts generated by standalone UAT tooling from uat_reports/.
No database required.
"""
from __future__ import annotations

from datetime import datetime
import difflib
import hashlib
import os
from pathlib import Path
import json
import subprocess
import sys
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException

router = APIRouter()

REPORT_GLOB = "*uat*.json"
PATCH_DIR_NAME = "patches"
RUN_LOG_FILE = "uat_runner.log"


_RUNNER_STATE: Dict[str, Any] = {
    "process": None,
    "started_at": None,
    "finished_at": None,
    "exit_code": None,
    "command": None,
    "log_path": None,
}


def _reports_dir() -> Path:
    # /repo/api/v1/endpoints/uat.py -> /repo
    repo_root = Path(__file__).resolve().parents[3]
    return repo_root / "uat_reports"


def _load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _save_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _latest_report_path() -> Path:
    reports_dir = _reports_dir()
    files = sorted(
        reports_dir.glob(REPORT_GLOB),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not files:
        raise HTTPException(status_code=404, detail="No UAT reports available")
    return files[0]


def _phase2_patch_dir() -> Path:
    return _reports_dir() / PATCH_DIR_NAME


def _pick_python_executable(repo_root: Path) -> str:
    venv_win = repo_root / ".venv" / "Scripts" / "python.exe"
    venv_unix = repo_root / ".venv" / "bin" / "python"
    if venv_win.exists():
        return str(venv_win)
    if venv_unix.exists():
        return str(venv_unix)
    return sys.executable


def _runner_status() -> Dict[str, Any]:
    proc: Optional[subprocess.Popen] = _RUNNER_STATE.get("process")
    running = False
    exit_code = _RUNNER_STATE.get("exit_code")

    if proc is not None:
        poll = proc.poll()
        if poll is None:
            running = True
        else:
            exit_code = poll
            _RUNNER_STATE["exit_code"] = poll
            _RUNNER_STATE["finished_at"] = _RUNNER_STATE.get("finished_at") or datetime.utcnow().isoformat()

    latest_report = None
    try:
        latest_report = _latest_report_path().name
    except Exception:
        latest_report = None

    return {
        "running": running,
        "started_at": _RUNNER_STATE.get("started_at"),
        "finished_at": _RUNNER_STATE.get("finished_at"),
        "exit_code": exit_code,
        "command": _RUNNER_STATE.get("command"),
        "log_path": _RUNNER_STATE.get("log_path"),
        "latest_report": latest_report,
    }


def _report_failure_profile(report: Dict[str, Any]) -> Dict[str, Any]:
    steps = report.get("steps", [])
    total = len(steps)
    failed = [s for s in steps if not s.get("success", False)]
    failed_count = len(failed)
    failure_pct = (failed_count / total * 100.0) if total else 0.0

    disconnected = 0
    server_errors = 0
    for step in failed:
        code = int(step.get("status_code", 0) or 0)
        err_text = str(step.get("error", ""))
        if code == 0 and "RemoteDisconnected" in err_text:
            disconnected += 1
        if 500 <= code <= 599:
            server_errors += 1

    return {
        "total_steps": total,
        "failed_steps": failed_count,
        "failure_pct": round(failure_pct, 2),
        "server_error_count": server_errors,
        "disconnect_count": disconnected,
    }


def _build_retry_hardening_patch() -> Dict[str, Any]:
    repo_root = Path(__file__).resolve().parents[3]
    target = repo_root / "agents" / "uat_enterprise_agent.py"
    if not target.exists():
        raise HTTPException(status_code=404, detail="Patch target file not found: agents/uat_enterprise_agent.py")

    original = target.read_text(encoding="utf-8")
    old_block = """    def _request(
        self,
        name: str,
        method: str,
        path: str,
        expected_status: Optional[List[int]] = None,
        required: bool = False,
        **kwargs: Any,
    ) -> Tuple[Optional[requests.Response], Any]:
        url = f\"{self.base_url}{API_PREFIX}{path}\"
        started = time.perf_counter()
        status_code = 0
        body: Any = None

        try:
            response = self.session.request(method, url, timeout=REQUEST_TIMEOUT, **kwargs)
            status_code = response.status_code
            latency_ms = (time.perf_counter() - started) * 1000.0
            self.latencies_ms.append(latency_ms)

            try:
                body = response.json()
            except Exception:
                body = response.text

            success = True
            if expected_status is not None and status_code not in expected_status:
                success = False

            self._record_step(
                name=name,
                method=method,
                path=path,
                status_code=status_code,
                latency_ms=latency_ms,
                success=success,
                details={\"url\": url},
                error=None if success else f\"Unexpected status: {status_code}\",
            )

            if required and not success:
                raise RuntimeError(f\"{name} failed with status {status_code}: {body}\")
            return response, body

        except Exception as exc:
            latency_ms = (time.perf_counter() - started) * 1000.0
            self.latencies_ms.append(latency_ms)
            self._record_step(
                name=name,
                method=method,
                path=path,
                status_code=status_code,
                latency_ms=latency_ms,
                success=False,
                error=str(exc),
            )
            if required:
                raise
            return None, None
"""
    new_block = """    def _request(
        self,
        name: str,
        method: str,
        path: str,
        expected_status: Optional[List[int]] = None,
        required: bool = False,
        **kwargs: Any,
    ) -> Tuple[Optional[requests.Response], Any]:
        url = f\"{self.base_url}{API_PREFIX}{path}\"
        started = time.perf_counter()
        status_code = 0
        body: Any = None
        max_retries = 2
        attempts = max_retries + 1
        retryable_server_codes = {500, 502, 503, 504}

        for attempt in range(1, attempts + 1):
            try:
                response = self.session.request(method, url, timeout=REQUEST_TIMEOUT, **kwargs)
                status_code = response.status_code

                try:
                    body = response.json()
                except Exception:
                    body = response.text

                success = expected_status is None or status_code in expected_status
                retryable_status = status_code in retryable_server_codes and attempt < attempts

                if not success and retryable_status:
                    time.sleep(0.2 * attempt)
                    continue

                latency_ms = (time.perf_counter() - started) * 1000.0
                self.latencies_ms.append(latency_ms)
                details = {\"url\": url, \"attempts\": attempt}
                self._record_step(
                    name=name,
                    method=method,
                    path=path,
                    status_code=status_code,
                    latency_ms=latency_ms,
                    success=success,
                    details=details,
                    error=None if success else f\"Unexpected status: {status_code}\",
                )

                if required and not success:
                    raise RuntimeError(f\"{name} failed with status {status_code}: {body}\")
                return response, body

            except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as exc:
                if attempt < attempts:
                    time.sleep(0.2 * attempt)
                    continue

                latency_ms = (time.perf_counter() - started) * 1000.0
                self.latencies_ms.append(latency_ms)
                self._record_step(
                    name=name,
                    method=method,
                    path=path,
                    status_code=status_code,
                    latency_ms=latency_ms,
                    success=False,
                    error=str(exc),
                )
                if required:
                    raise
                return None, None

            except Exception as exc:
                latency_ms = (time.perf_counter() - started) * 1000.0
                self.latencies_ms.append(latency_ms)
                self._record_step(
                    name=name,
                    method=method,
                    path=path,
                    status_code=status_code,
                    latency_ms=latency_ms,
                    success=False,
                    error=str(exc),
                )
                if required:
                    raise
                return None, None

        return None, None
"""

    # If already patched, return an explicit no-op signal rather than hard failing.
    if new_block in original:
        return {
            "recipe_id": "retry_hardening_uat_agent_v1",
            "title": "Add retries for transient UAT transport and 5xx failures",
            "target_file": "agents/uat_enterprise_agent.py",
            "already_applied": True,
            "patch": "",
            "patch_sha256": None,
        }

    if old_block not in original:
        raise HTTPException(
            status_code=409,
            detail=(
                "Could not generate retry patch because target code block no longer matches expected baseline. "
                "Regenerate recipe with latest file context."
            ),
        )

    updated = original.replace(old_block, new_block, 1)

    diff_lines = list(
        difflib.unified_diff(
            original.splitlines(),
            updated.splitlines(),
            fromfile="a/agents/uat_enterprise_agent.py",
            tofile="b/agents/uat_enterprise_agent.py",
            lineterm="",
        )
    )
    patch_text = "\n".join(diff_lines) + "\n"
    patch_hash = hashlib.sha256(patch_text.encode("utf-8")).hexdigest()

    return {
        "recipe_id": "retry_hardening_uat_agent_v1",
        "title": "Add retries for transient UAT transport and 5xx failures",
        "target_file": "agents/uat_enterprise_agent.py",
        "patch": patch_text,
        "patch_sha256": patch_hash,
    }


def _summary_from_report(path: Path, report: Dict[str, Any]) -> Dict[str, Any]:
    summary = report.get("summary", {})
    top_failures: Dict[str, int] = {}
    for step in report.get("steps", []):
        if not step.get("success", False):
            key = f"{step.get('method', 'UNK')} {step.get('path', 'UNKNOWN')} -> {step.get('status_code', 0)}"
            top_failures[key] = top_failures.get(key, 0) + 1

    top_failures_sorted = sorted(
        [{"endpoint": k, "count": v} for k, v in top_failures.items()],
        key=lambda x: x["count"],
        reverse=True,
    )[:10]

    return {
        "file": path.name,
        "path": str(path),
        "last_modified": datetime.fromtimestamp(path.stat().st_mtime).isoformat(),
        "run_id": report.get("run_id"),
        "started_at": report.get("started_at"),
        "finished_at": report.get("finished_at"),
        "summary": {
            "total_steps": summary.get("total_steps", len(report.get("steps", []))),
            "failed_steps": summary.get("failed_steps", 0),
            "success_rate_pct": summary.get("success_rate_pct", 0),
            "p95_latency_ms": summary.get("p95_latency_ms"),
            "improvement_candidates": summary.get("improvement_candidates", len(report.get("improvement_candidates", []))),
        },
        "top_failures": top_failures_sorted,
    }


@router.get("/reports")
def list_uat_reports(limit: int = 30) -> Dict[str, Any]:
    reports_dir = _reports_dir()
    if not reports_dir.exists():
        return {"reports_dir": str(reports_dir), "reports": [], "count": 0}

    files = sorted(
        reports_dir.glob(REPORT_GLOB),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )[: max(1, min(limit, 100))]

    reports: List[Dict[str, Any]] = []
    for p in files:
        try:
            report = _load_json(p)
            reports.append(_summary_from_report(p, report))
        except Exception as exc:
            reports.append(
                {
                    "file": p.name,
                    "path": str(p),
                    "last_modified": datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
                    "error": f"Could not parse report: {exc}",
                }
            )

    return {"reports_dir": str(reports_dir), "count": len(reports), "reports": reports}


@router.get("/reports/{report_file}")
def get_uat_report(report_file: str) -> Dict[str, Any]:
    reports_dir = _reports_dir()
    path = (reports_dir / report_file).resolve()

    if reports_dir.resolve() not in path.parents and path != reports_dir.resolve():
        raise HTTPException(status_code=400, detail="Invalid report file path")
    if not path.exists() or not path.is_file():
        raise HTTPException(status_code=404, detail="Report not found")

    try:
        report = _load_json(path)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Invalid JSON report: {exc}")

    return {
        "file": path.name,
        "path": str(path),
        "last_modified": datetime.fromtimestamp(path.stat().st_mtime).isoformat(),
        "report": report,
    }


@router.get("/compare/latest")
def compare_latest() -> Dict[str, Any]:
    reports_dir = _reports_dir()
    if not reports_dir.exists():
        raise HTTPException(status_code=404, detail="No uat_reports directory found")

    files = sorted(
        reports_dir.glob(REPORT_GLOB),
        key=lambda p: p.stat().st_mtime,
    )
    if len(files) < 2:
        raise HTTPException(status_code=404, detail="Need at least 2 reports to compare")

    old_path = files[-2]
    new_path = files[-1]
    old = _load_json(old_path)
    new = _load_json(new_path)

    old_sum = old.get("summary", {})
    new_sum = new.get("summary", {})

    def fail_map(report: Dict[str, Any]) -> Dict[str, int]:
        m: Dict[str, int] = {}
        for step in report.get("steps", []):
            if not step.get("success", False):
                key = f"{step.get('method', 'UNK')} {step.get('path', 'UNKNOWN')}"
                m[key] = m.get(key, 0) + 1
        return m

    old_fail = fail_map(old)
    new_fail = fail_map(new)

    deltas: Dict[str, int] = {}
    for key in set(old_fail.keys()) | set(new_fail.keys()):
        deltas[key] = new_fail.get(key, 0) - old_fail.get(key, 0)

    improvements = sorted(
        [{"endpoint": k, "delta": v} for k, v in deltas.items() if v < 0],
        key=lambda x: x["delta"],
    )
    regressions = sorted(
        [{"endpoint": k, "delta": v} for k, v in deltas.items() if v > 0],
        key=lambda x: x["delta"],
        reverse=True,
    )

    return {
        "old_file": old_path.name,
        "new_file": new_path.name,
        "summary": {
            "old_total_steps": old_sum.get("total_steps", len(old.get("steps", []))),
            "new_total_steps": new_sum.get("total_steps", len(new.get("steps", []))),
            "old_failed_steps": old_sum.get("failed_steps", 0),
            "new_failed_steps": new_sum.get("failed_steps", 0),
            "old_success_rate_pct": old_sum.get("success_rate_pct", 0),
            "new_success_rate_pct": new_sum.get("success_rate_pct", 0),
            "old_p95_latency_ms": old_sum.get("p95_latency_ms"),
            "new_p95_latency_ms": new_sum.get("p95_latency_ms"),
        },
        "improvements": improvements[:15],
        "regressions": regressions[:15],
    }


@router.post("/run/start")
def start_uat_run(payload: Dict[str, Any] = Body(default={})) -> Dict[str, Any]:
    current = _runner_status()
    if current["running"]:
        raise HTTPException(status_code=409, detail={"message": "UAT run already in progress", "status": current})

    scale = str(payload.get("scale") or "deep").lower()
    if scale not in {"small", "medium", "deep"}:
        raise HTTPException(status_code=400, detail="scale must be one of: small, medium, deep")

    seed = int(payload.get("seed", 42))
    base_url = str(payload.get("base_url") or "http://127.0.0.1:8000")

    repo_root = Path(__file__).resolve().parents[3]
    py_exec = _pick_python_executable(repo_root)
    cmd = [
        py_exec,
        str(repo_root / "agents" / "uat_enterprise_agent.py"),
        "--base-url",
        base_url,
        "--scale",
        scale,
        "--seed",
        str(seed),
    ]

    log_path = _reports_dir() / RUN_LOG_FILE
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_fp = open(log_path, "a", encoding="utf-8")
    log_fp.write(f"\n[{datetime.utcnow().isoformat()}] START {' '.join(cmd)}\n")
    log_fp.flush()

    proc = subprocess.Popen(
        cmd,
        cwd=repo_root,
        stdout=log_fp,
        stderr=log_fp,
    )

    _RUNNER_STATE["process"] = proc
    _RUNNER_STATE["started_at"] = datetime.utcnow().isoformat()
    _RUNNER_STATE["finished_at"] = None
    _RUNNER_STATE["exit_code"] = None
    _RUNNER_STATE["command"] = cmd
    _RUNNER_STATE["log_path"] = str(log_path)

    return {
        "started": True,
        "pid": proc.pid,
        "status": _runner_status(),
    }


@router.get("/run/status")
def get_uat_run_status() -> Dict[str, Any]:
    return _runner_status()


@router.post("/run/stop")
def stop_uat_run() -> Dict[str, Any]:
    proc: Optional[subprocess.Popen] = _RUNNER_STATE.get("process")
    if proc is None or proc.poll() is not None:
        return {"stopped": False, "status": _runner_status(), "message": "No active run"}

    proc.terminate()
    try:
        proc.wait(timeout=8)
    except Exception:
        proc.kill()

    _RUNNER_STATE["finished_at"] = datetime.utcnow().isoformat()
    _RUNNER_STATE["exit_code"] = proc.poll()
    return {"stopped": True, "status": _runner_status()}


@router.post("/phase2/plan")
def phase2_plan(payload: Dict[str, Any] = Body(default={})) -> Dict[str, Any]:
    report_file = payload.get("report_file")
    if report_file:
        report_path = (_reports_dir() / str(report_file)).resolve()
        if not report_path.exists():
            raise HTTPException(status_code=404, detail=f"Report not found: {report_file}")
    else:
        report_path = _latest_report_path()

    report = _load_json(report_path)
    profile = _report_failure_profile(report)

    recipes: List[Dict[str, Any]] = []
    if profile["disconnect_count"] > 0 or profile["server_error_count"] > 0:
        recipes.append(
            {
                "recipe_id": "retry_hardening_uat_agent_v1",
                "title": "Add retries for transient UAT failures",
                "reason": (
                    f"Detected {profile['disconnect_count']} disconnects and "
                    f"{profile['server_error_count']} server errors in report."
                ),
            }
        )

    return {
        "phase": "phase2_plan",
        "report_file": report_path.name,
        "failure_profile": profile,
        "recommended_recipes": recipes,
        "next": "Call /api/v1/uat/phase2/patch with a recipe_id",
    }


@router.post("/phase2/patch")
def phase2_patch(payload: Dict[str, Any] = Body(default={})) -> Dict[str, Any]:
    recipe_id = str(payload.get("recipe_id") or "retry_hardening_uat_agent_v1")
    if recipe_id != "retry_hardening_uat_agent_v1":
        raise HTTPException(status_code=400, detail=f"Unsupported recipe_id: {recipe_id}")

    patch_obj = _build_retry_hardening_patch()

    if patch_obj.get("already_applied"):
        return {
            "phase": "phase2_patch",
            "recipe_id": patch_obj["recipe_id"],
            "title": patch_obj["title"],
            "target_file": patch_obj["target_file"],
            "already_applied": True,
            "message": "Retry hardening is already present in agents/uat_enterprise_agent.py",
            "next": "Run UAT again and compare latest runs",
        }

    stamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    patch_file = f"{patch_obj['recipe_id']}_{stamp}.patch"
    patch_path = _phase2_patch_dir() / patch_file
    _save_text(patch_path, patch_obj["patch"])

    return {
        "phase": "phase2_patch",
        "recipe_id": patch_obj["recipe_id"],
        "title": patch_obj["title"],
        "patch_file": patch_file,
        "patch_path": str(patch_path),
        "patch_sha256": patch_obj["patch_sha256"],
        "target_file": patch_obj["target_file"],
        "next": "Call /api/v1/uat/phase2/apply with patch_file and confirm=true",
    }


@router.post("/phase2/apply")
def phase2_apply(payload: Dict[str, Any] = Body(default={})) -> Dict[str, Any]:
    patch_file = payload.get("patch_file")
    confirm = bool(payload.get("confirm", False))

    if not patch_file:
        raise HTTPException(status_code=400, detail="patch_file is required")

    patch_path = (_phase2_patch_dir() / str(patch_file)).resolve()
    patch_dir = _phase2_patch_dir().resolve()
    if patch_dir not in patch_path.parents and patch_path != patch_dir:
        raise HTTPException(status_code=400, detail="Invalid patch path")
    if not patch_path.exists():
        raise HTTPException(status_code=404, detail=f"Patch file not found: {patch_file}")

    repo_root = Path(__file__).resolve().parents[3]
    env = os.environ.copy()
    apply_check_cmd = ["git", "apply", "--check", str(patch_path)]
    apply_cmd = ["git", "apply", str(patch_path)]

    check_proc = subprocess.run(
        apply_check_cmd,
        cwd=repo_root,
        text=True,
        capture_output=True,
        env=env,
    )
    if check_proc.returncode != 0:
        return {
            "phase": "phase2_apply",
            "applied": False,
            "confirm_required": True,
            "check_passed": False,
            "stderr": check_proc.stderr,
            "stdout": check_proc.stdout,
        }

    if not confirm:
        return {
            "phase": "phase2_apply",
            "applied": False,
            "confirm_required": True,
            "check_passed": True,
            "message": "Patch validated. Re-submit with confirm=true to apply.",
        }

    apply_proc = subprocess.run(
        apply_cmd,
        cwd=repo_root,
        text=True,
        capture_output=True,
        env=env,
    )
    if apply_proc.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail={
                "message": "Patch apply failed",
                "stdout": apply_proc.stdout,
                "stderr": apply_proc.stderr,
            },
        )

    # Quick syntax validation of the patched file.
    validate_cmd = [sys.executable, "-m", "py_compile", "agents/uat_enterprise_agent.py"]
    validate_proc = subprocess.run(
        validate_cmd,
        cwd=repo_root,
        text=True,
        capture_output=True,
        env=env,
    )

    return {
        "phase": "phase2_apply",
        "applied": True,
        "patch_file": patch_file,
        "check_passed": True,
        "validation": {
            "command": " ".join(validate_cmd),
            "returncode": validate_proc.returncode,
            "stdout": validate_proc.stdout,
            "stderr": validate_proc.stderr,
        },
    }
